---
apiVersion: v1
kind: Service
metadata:
  name: monitoring-be-service-32118
  labels:
    app: monitoring-be-service-32118
spec:
  type: NodePort
  ports:
    - port: 9998
      targetPort: 9998
      nodePort: 32118
      name: http
  selector:
    app: monitoring-be-32118
---
apiVersion: v1
kind: Pod
metadata:
  name: monitoring-be-32118
  labels: 
    app: monitoring-be-32118
spec:
  containers:
  - name: monitoring-be-service-32118-deployment
    image: '{{.Values.imagelocation.domainname}}/{{.Values.imagelocation.project}}/monitoring-be-service:latest'
    imagePullPolicy: IfNotPresent
    ports:
      - containerPort: 9997
    env:
      - name: LISTEN_IP
        value: 0.0.0.0
      - name: FE_SERVICE
        value: "monitoring-proxy-service-32117:5000"
      - name: MEP_AGENT
        value: 127.0.0.1:8080
  - name: mep-agent
    image: '{{.Values.imagelocation.domainname}}/{{.Values.imagelocation.project}}/mep-agent-x86:latest'
    imagePullPolicy: IfNotPresent
    env:
      - name: ENABLE_WAIT
        value: "true"
      - name: MEP_IP
        value: "mep-api-gw.mep"
      - name: MEP_APIGW_PORT
        value: "8443"
      - name: CA_CERT_DOMAIN_NAME
        value: "edgegallery"
      - name: CA_CERT
        value: /usr/mep/ssl/ca.crt
      - name: AK
        valueFrom:
          secretKeyRef:
            name: {{ .Values.appconfig.aksk.secretname }}
            key: accesskey
      - name: SK
        valueFrom:
          secretKeyRef:
            name: {{ .Values.appconfig.aksk.secretname }}
            key: secretkey
      - name: APPINSTID
        valueFrom:
          secretKeyRef:
            name: {{ .Values.appconfig.aksk.secretname }}
            key: appInsId
    volumeMounts:
      - name: mep-agent-service-config-volume
        mountPath: /usr/mep/conf/app_instance_info.yaml
        subPath: app_instance_info.yaml
              
  volumes:
    - name: mep-agent-service-config-volume
      configMap:
        name: {{ .Values.global.mepagent.configmapname }}   
---
apiVersion: v1
kind: Service
metadata:
  name: monitoring-fe-service-32119
  labels:
    app: monitoring-fe-service-32119
spec:
  type: NodePort
  ports:
  - port: 8081
    targetPort: 8081
    nodePort: 32119
    name: http

  selector:
    app: monitoring-fe-32119

---
apiVersion: v1
kind: Pod
metadata:
  name: monitoring-fe-32119
  labels: 
    app: monitoring-fe-32119
spec:
  containers:
  - name: monitoring-fe-service-32119-deployment
    image: '{{.Values.imagelocation.domainname}}/{{.Values.imagelocation.project}}/monitoring-fe-service:latest'
    imagePullPolicy: IfNotPresent
    ports:
      - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: monitoring-proxy-service-32120
  labels:
    app: monitoring-proxy-service-32120
spec:
  type: NodePort
  ports:
  - port: 5001
    targetPort: 5001
    nodePort: 32120
    name: http
  selector:
    app: monitoring-proxy-32120
---
apiVersion: v1
kind: Pod
metadata:
  name: monitoring-proxy-32120
  labels: 
    app: monitoring-proxy-32120
spec:
  containers:
  - name: monitoring-proxy-service-32120-deployment
    image: '{{.Values.imagelocation.domainname}}/{{.Values.imagelocation.project}}/monitoring-proxy-service:latest'
    imagePullPolicy: IfNotPresent
    ports:
      - containerPort: 5000
    env:
      - name: EXPOSE_PORT
        value: "32120"
